### ISSUE TITLE
Some confusions about code

### ISSUE THREAD

**Issue by zhangc-ops** [giannismpartsiokas/thesis_progect_etsi_TR_138_901_5g_channel_modeling#2]
this is the warnning when I run the code "test_simul_5G.m":
"The file'H_generated.mat' could not be read.  There are no such files or directories."
Having read the issues before,I just don't know where this file you uploaded.
Looking forward to your reply.

**Comment by giannismpartsiokas** [comment]
Please refer bach to the other issue! Thanks a lot!!
